### ISSUE TITLE
Changing font size changes also the font size of the buttons Find, Replace,All and the fields for the search and replace value

### ISSUE THREAD

**Issue by matthiasrebbe** [mwieder/glx2ScriptEditor#1]
Changing the font size changes also the fonsize of the 2 fields for the find and replace values and also the text size of the buttons "find", "replace" and "all".

But this is not seen immediately. When changing font size only the change in the script editor window is visible. But after a restart of GLX2 also the textsize of the above mentioned fields and buttons has changed.
So larger font sizes make at least the buttons not completely readable

<img width="1509" alt="glx-fontsize" src="https://user-images.githubusercontent.com/9978143/82644296-60c32400-9c11-11ea-9a8f-e89e80734690.png">

**Comment by mwieder** [comment]
Fixed in the latest build. I'm assigning a fixed font size to the Find/Replace text row now.
