### ISSUE TITLE
Handler links don't work?

### ISSUE THREAD

**Issue by macMikey** [mwieder/glx2ScriptEditor#11]
I don't see any sort of callout for handlers that are not in the current script
<img width="1134" alt="Screen Shot 2021-04-01 at 10 58 23" src="https://user-images.githubusercontent.com/10867016/113313532-55cd2b80-92d9-11eb-8750-3c3c9a56af46.png">

**Comment by mwieder** [comment]
If you open the "all handlers" folder you should see the mouseUp handler there.

**Comment by macMikey** [comment]
Same screenshot, different issue.  On this issue, you can see that *sync* is not italicized, even though the handler is in another script.

**Comment by mwieder** [comment]
Yeah. I've had to give up italicizing external links for now until I can unmangle the styledText array to the point where I don't lose all the formatting when italicizing a link. Not really sure it's feasible atm.

**Comment by mwieder** [comment]
Italicized external links should be working now in 4.1.19.
