### ISSUE TITLE
Not all handler names appearing in the handler list

### ISSUE THREAD

**Issue by macMikey** [mwieder/glx2ScriptEditor#12]
Here's a simple example - no mouseUp listed, but I see this in more complicated scripts, too:
<img width="1134" alt="Screen Shot 2021-04-01 at 10 58 23" src="https://user-images.githubusercontent.com/10867016/113313706-80b77f80-92d9-11eb-9550-e90ff9d2e040.png">

**Comment by macMikey** [comment]
You are correct (on the link issue) that if I had single-clicked on the folder, the handler would show. I was trying to not show a more complicated stack script, where only some of the handlers appear:
As you can see in this screenshot, neither the *preOpenStack* nor the *openStack* handlers appear (among others)
<img width="437" alt="Screen Shot 2021-04-01 at 19 42 21" src="https://user-images.githubusercontent.com/10867016/113364826-7e2d4800-9322-11eb-9d5e-8510fcd4bd7e.png">

**Comment by mwieder** [comment]
OK - that's weird. Lemme check it out.

**Comment by mwieder** [comment]
I'm not noticing any missing handlers now... see what you think.

**Comment by macMikey** [comment]
Did you push an update?

**Comment by macMikey** [comment]
Still broken.
I have a glx2 folder declared part-way down. Nothing above that displays in the list.

**Comment by mwieder** [comment]
OK - I'll get on it. Thanks.

**Comment by mwieder** [comment]
Ah - I was misunderstanding the issue you were reporting. I've got sort of a kludge in 4.1.19 to take care of this now. It's all working properly (there's an 'all handlers') folder for the unhoused handlers). The only weird part is that if you then add a folder, remove it, and add it again, then there's an empty 'all handlers' folder at the start. At present the only way I can think of to get around this is even more of a kludge, so it's on my todo list for someday and just an occasional annoyance now.

**Comment by macMikey** [comment]
I don't even see an "All Handlers" folder.

**Comment by macMikey** [comment]
whoops - ignore - latest has it
