### ISSUE TITLE
If toolbar text and toolbar icons are not displayed, GLX2 menubar does not display

### ISSUE THREAD

**Issue by macMikey** [mwieder/glx2ScriptEditor#13]
I generally don't show the toolbar text or the toolbar icons. By not showing either of them, the GLX toolbar does not display, either.

**Comment by mwieder** [comment]
I filed a PR to fix this over a year ago. The PR writeup addresses linux in particular, but Bad Things happen if you disable both. I've just resigned myself to showing text until this gets fixed. But the glx2 toolbar does show up for me, even though the IDE is nonresponsive.

https://github.com/livecode/livecode-ide/pull/2118

**Comment by mwieder** [comment]
Closing this since it's not something under my control. If the team ever gets around to implementing my pull request this will no longer be a problem.
