### ISSUE TITLE
Update breaks install

### ISSUE THREAD

**Issue by macMikey** [mwieder/glx2ScriptEditor#16]
1. Fetch commit 86f836d146dd8f867d5f00029f1d4453f563e38f
2. Copy files to *myLivecode/Plugins*
3. Fire up LC
4. Get a dialog saying that 4.1.1.9 is available to install (?)
<img width="400" alt="Screen Shot 2021-04-05 at 07 11 26" src="https://user-images.githubusercontent.com/10867016/113568273-3b979400-95de-11eb-8494-0526b7c18e8a.png">

5. Hit "Yes"
6. Quit LC
7. Fire up LC
8. glx is gone - title bar is gone and the plugin does not appear in the list of plugins

**Comment by mwieder** [comment]
Fixed. Ugh - github won't download the binary file inside the "Place in your plugins folder" folder.

**Comment by macMikey** [comment]
What does that mean? If you have a binary file in a repo it goes when you
check out the branch.

**Comment by mwieder** [comment]
yep - but you can't download a binary file from github directly with it redirecting the url internally and then you end up with a bunch of html instead of the binary file.

**Comment by macMikey** [comment]
Sorry - still confused - why do you have to download at all? Were you
hosting the binary in the repo and then hoping to download the updates
directly?

**Comment by mwieder** [comment]
Ah - so you're reinstalling from the git repo?
The binary image is there so that when you have the automated check for update enabled it allows you to download a new binary image when one is available.
The checkbox is at the bottom of the preferences panel.

**Comment by mwieder** [comment]
The auto update feature is now working in build 4.1.19b.
