### ISSUE TITLE
update does not install

### ISSUE THREAD

**Issue by macMikey** [mwieder/glx2ScriptEditor#18]
Regardless of the number of times that you say "yes", every time i launch LC, the update dialog pops up.
<img width="399" alt="Screen Shot 2021-05-13 at 08 59 19" src="https://user-images.githubusercontent.com/10867016/118129010-a308e680-b3c9-11eb-9b3d-816fa06c130d.png">

**Comment by mwieder** [comment]
Yeah, sorry about that. It's a bug in the update check function in the previous version. You'll have to install the new build manually. Should be fine after that.
