### ISSUE TITLE
Font size set in GLX settings is reset to 14 after GLX2 editor window is closed or LC is restarted

### ISSUE THREAD

**Issue by matthiasrebbe** [mwieder/glx2ScriptEditor#19]
Hi,
the font settings are not saved permanently. Changing the size to an other value than the default one (14) changes the size in the opened editor window. But when closing and reopening the editor window shows the text again in the default size of 14. The same happens if LC is closed and restarted right away after the font size was changed.
The prefs file btw. always show 14 as font size, although the other settings were saved correctly.

**Comment by mwieder** [comment]
Again? I thought I fixed this a few months ago. I'll check - possibly I never uploaded the latest build.

**Comment by mwieder** [comment]
Fixed and uploaded as version 4.2.1. Thanks for finding that. I rarely ever change font size, so these things are easy to slip by.
