### ISSUE TITLE
enabled CAP control structures  settings do not work correctly

### ISSUE THREAD

**Issue by matthiasrebbe** [mwieder/glx2ScriptEditor#20]
enabled CAP control structures settings do not work correctly

**if then else endif** are completely left lower case

switch: only   **case, default ** and **end switch** are changed to upper cases. The beginning switch is left lower case

**on, function, repeat, setprop, getprop, try** : END is changed uppercase, the inital keyword is not

**Comment by mwieder** [comment]
Fixed for version 4.2.2.
Sorry - this isn't a feature I use, so it took some time to figure out what's going on and how to deal with it.
