### ISSUE TITLE
Complete on Return - Switch control structure:  a 'break" is placed after 'default'

### ISSUE THREAD

**Issue by matthiasrebbe** [mwieder/glx2ScriptEditor#21]
When the _switch control structure_ is completed on return then not only after **case** the **break** keyword is placed, but also after **default**. 

this is how it looks after completion. 

```
switch tCheck
CASE ""

break
DEFAULT

break
END SWITCH -- tCheck
```

**Comment by mwieder** [comment]
Yes - that's there by design. Note that the "default" option doesn't necessarily have to be the last in the list, so the break command is there to ensure that the code won't fall through to any following options unless the break is explicitly removed.
