### ISSUE TITLE
wrong date for 4.1.4

### ISSUE THREAD

**Issue by matthiasrebbe** [mwieder/glx2ScriptEditor#5]
Shouldn't the date in the readme.md for version 4.1.4 **2020.06.13**?

**Comment by mwieder** [comment]
Ha! Yes, it certainly should. Too much cut-and-paste. In other news, I've been able to replicate the problem you're seeing with not being able to edit without toggling glx2 on and off first, but only on osx. I can get it to happen with no other plugins in the system, so there's no conflict with them. Looking into it now.

**Comment by mwieder** [comment]
The date for version 4.1.7 is 2020.12.21.
