### ISSUE TITLE
code folding triangles are shown in an empty script and force cursor to jump back and some other

### ISSUE THREAD

**Issue by matthiasrebbe** [mwieder/glx2ScriptEditor#6]
When editing a new script for an object, GLX2 now shows line numbers and also already placeds code folding triangles at line 1, 6, 14, 18,20

It is not possible to press Enter in line 6 as long as line 6 is empty. The cursor jumps back.
If line 6 contains text and one is able to press enter to jump to line 7. And there again it is not possible to press enter until some text is in line 7 and so on.

Opening an existing script those wrong triangles are also shown , but also correct ones.

When opening/creating a 2nd script in GLX2, regardless if new or already existing,  while the first script is still opened in GLX, then the font size of the new script is smaller (maybe the default size) than the configured one and typing is almost impossible as it is awfully slow, but all triangles are missing, even the correct ones.

Here´s a screen recording show the described behaviours.
https://livecode.dermattes.de/glx2/GLX2_4_14.mp4

**Comment by mwieder** [comment]
I believe this is all fixed now with the latest version.
