### ISSUE TITLE
[Suggestion] Re Installation

### ISSUE THREAD

**Issue by macMikey** [mwieder/glx2ScriptEditor#7]
The installation instructions could be more direct:
1. Copy glxScriptEditor.rev to your Plugins folder (describe path on each platform)
2. Copy glx2Plugins.txt to your Plugins folder (describe path on each platform)

To that end, I would suggest also adding a folder to the repo, called something like "Put in LC Plugins Folder" and place both of those files in that folder.

**Comment by mwieder** [comment]
Nice idea. I'm constrained by a computer crash at the moment, but I'll make that change for the next push.

**Comment by mwieder** [comment]
Done.
