### ISSUE TITLE
goto definition doesn't

### ISSUE THREAD

**Issue by macMikey** [mwieder/glx2ScriptEditor#9]
1. Select a handler that is in a different script
2. Choose *goto definition*
Nothing happens.
Switch to the card editor, find the handler name, and it shows up.

**Comment by mwieder** [comment]
Not sure what this means. Selecting 'go to definition" works for me when the target is in a different script. What's a 'card editor'?

**Comment by macMikey** [comment]
Weird.  It doesn't even recognize the handler for me.

**Comment by mwieder** [comment]
OK - that's a bit bizarre - are you sure the handler exists? Do you have a sample stack you can paste here?

**Comment by macMikey** [comment]
I'm 100% sure.  If I switch from glx2 to the SE, it behaves as expected.
Probably the first thing to do is disable the other plugins and see what happens.

**Comment by macMikey** [comment]
disabling seth seems to have resolved this
